### ISSUE TITLE
Returned post ReadCSV example

### ISSUE THREAD

**Issue by julioflima** [fivitti/Arduino-CSV-File#1]
> 

In file included from C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master\examples\ReadCSV\ReadCSV.ino:15:0:

C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master/CSVFile.h:16:32: error: expected class-name before '{' token

 class CSVFile : public FatFile {

                                ^

C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master/CSVFile.h:137:17: error: 'FatFile' has not been declared

  byte copyField(FatFile * target);

                 ^

C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master/CSVFile.h: In constructor 'CSVFile::CSVFile()':

C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master/CSVFile.h:35:14: error: class 'CSVFile' does not have any field named 'FatFile'

  CSVFile() : FatFile() {}

              ^

C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master\examples\ReadCSV\ReadCSV.ino: In function 'void initSdFile()':

ReadCSV:78: error: 'class CSVFile' has no member named 'open'

   if (!csv.open(FILENAME, O_RDWR | O_CREAT)) {

            ^

C:\Program Files (x86)\Arduino\libraries\Arduino-CSV-File-master\examples\ReadCSV\ReadCSV.ino: In function 'void loop()':

ReadCSV:100: error: 'class CSVFile' has no member named 'write'

   csv.write("One;Two;Three\n"); 

       ^

ReadCSV:101: error: 'class CSVFile' has no member named 'write'

   csv.write("Very long long field.;Second long field.\n"); 

       ^

ReadCSV:102: error: 'class CSVFile' has no member named 'write'

   csv.write("zaÅ¼Ã³Å‚Ä‡ gÄ™Å›lÄ… jaÅºÅ„\n");

       ^

ReadCSV:103: error: 'class CSVFile' has no member named 'write'

   csv.write("11;22\0;3df;null\n");

       ^

ReadCSV:104: error: 'class CSVFile' has no member named 'write'

   csv.write(";");

       ^

ReadCSV:206: error: 'class CSVFile' has no member named 'close'

   csv.close();

       ^

exit status 1
'class CSVFile' has no member named 'open'

**Comment by fivitti** [comment]
Hi!
Are you sure that you have SdFat library in your Arduino libraries directory?
You must place [SdFat](https://github.com/greiman/SdFat) in C:\Users\YOUR_USERNAME\Documents\Arduino\libraries (default directory) first.
I see that your IDE not found "FatFile" class. This class is part of SdFat library. My CSVFile inherit this class.
