### ISSUE TITLE
hust have 1 row

### ISSUE THREAD

**Issue by majidmp97** [fivitti/Arduino-CSV-File#2]
**hello i test your program and lib
but just write in 1 row A
how can i write in other (a . b.c.d.e..)row ?
![csv](https://user-images.githubusercontent.com/35567123/41835448-e0508e44-786c-11e8-8627-4c32c0d03d4c.JPG)**

**Comment by majidmp97** [comment]
i cheek csv.csv
your example output file save with ; and bocuse of that we cannot make new row
i make csv file in pc look like photo and i figure out in notepad++  csv  in pc make row with ,
if you change lib to , we can make new row lookalike photo
![csv2](https://user-images.githubusercontent.com/35567123/41839018-53769da0-7877-11e8-94ff-3730978ee9ba.JPG)

**Comment by fivitti** [comment]
Hi!
You can change the field's delimiter by editing [CSVFileConfig.h](https://github.com/fivitti/Arduino-CSV-File/blob/master/CSVFileConfig.h).

You should change line:
`#define CSV_FILE_DELIMITER ';'`
with:
`#define CSV_FILE_DELIMITER ','`

The possibility to change the delimiter is easy to implement. I add it in next revision (not planned in short time).

**Comment by majidmp97** [comment]
**i manage make csv table witout your lib

`/*
 *  Arduino SD Card csv Example
 *  
 *  by majiq
 */
#include <SD.h>
#include <SPI.h>
File myFile;
int pinCS = 10; // Pin 10 on Arduino Uno
void setup() {
   Serial.begin(115200);
  pinMode(pinCS, OUTPUT); 
  // SD Card Initialization
  if (SD.begin())
  {
    Serial.println("SD card is ready to use.");
  } else
  {
    Serial.println("SD card initialization failed");
    return;
  }
  
  // Create/Open file 
  myFile = SD.open("test.csv", FILE_WRITE);
  
  // if the file opened okay, write to it:
  if (myFile) {
    Serial.println("Writing to file...");
    // Write to file
    myFile.println("Testing text a, b ,c, b ,c, b ,c, b ,c");
    myFile.println("Testing text 1, 2 ,3, 2 ,3, 2 ,3, 2 ,3");

    
    myFile.close(); // close the file
    Serial.println("Done.");
  }
  // if the file didn't open, print an error:
  else {
    Serial.println("error opening test.txt");
  }
  // Reading the file
  myFile = SD.open("test.csv");
  if (myFile) {
    Serial.println("Read:");
    // Reading the whole file
    while (myFile.available()) {
      Serial.write(myFile.read());
   }
    myFile.close();
  }
  else {
    Serial.println("error opening test.txt");
  }
  
}
void loop() {
  // empty
}`**
